import { Comic } from "./types";

export const mockComics: Comic[] = [
  {
    id: "1",
    repoName: "shadcn/ui",
    repoUrl: "https://github.com/shadcn/ui",
    stars: 45230,
    language: "TypeScript",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "Beautifully designed components built with Radix UI and Tailwind CSS",
      "Copy and paste into your apps - not a traditional component library",
      "Fully customizable and accessible by default",
    ],
    isNew: true,
    likes: 1234,
    shares: 89,
    comments: 56,
    createdAt: "2025-10-01T10:00:00Z",
  },
  {
    id: "2",
    repoName: "vercel/next.js",
    repoUrl: "https://github.com/vercel/next.js",
    stars: 118450,
    language: "JavaScript",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "The React Framework for Production",
      "Hybrid static & server rendering, TypeScript support",
      "Smart bundling, route pre-fetching, and more",
    ],
    isNew: false,
    likes: 5678,
    shares: 234,
    comments: 123,
    createdAt: "2025-09-30T15:30:00Z",
  },
  {
    id: "3",
    repoName: "microsoft/playwright",
    repoUrl: "https://github.com/microsoft/playwright",
    stars: 58900,
    language: "TypeScript",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "Cross-browser end-to-end testing framework",
      "Supports Chromium, Firefox, and WebKit",
      "Auto-wait, network interception, and more",
    ],
    isNew: true,
    likes: 892,
    shares: 45,
    comments: 34,
    createdAt: "2025-10-01T08:00:00Z",
  },
  {
    id: "4",
    repoName: "rust-lang/rust",
    repoUrl: "https://github.com/rust-lang/rust",
    stars: 89120,
    language: "Rust",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "A language empowering everyone to build reliable and efficient software",
      "Memory safety without garbage collection",
      "Zero-cost abstractions and fearless concurrency",
    ],
    isNew: false,
    likes: 3456,
    shares: 178,
    comments: 92,
    createdAt: "2025-09-29T12:00:00Z",
  },
  {
    id: "5",
    repoName: "facebook/react",
    repoUrl: "https://github.com/facebook/react",
    stars: 215340,
    language: "JavaScript",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "A declarative, efficient, and flexible JavaScript library for building UIs",
      "Component-based architecture for reusable code",
      "Virtual DOM for optimal performance",
    ],
    isNew: false,
    likes: 8901,
    shares: 456,
    comments: 234,
    createdAt: "2025-09-28T09:00:00Z",
  },
  {
    id: "6",
    repoName: "tensorflow/tensorflow",
    repoUrl: "https://github.com/tensorflow/tensorflow",
    stars: 178560,
    language: "Python",
    panels: [
      "https://placehold.co/600x400/161B22/58A6FF?text=Panel+1",
      "https://placehold.co/600x400/161B22/3FB950?text=Panel+2",
    ],
    keyInsights: [
      "End-to-end open source platform for machine learning",
      "Comprehensive ecosystem of tools and libraries",
      "Deploy ML models anywhere from cloud to edge devices",
    ],
    isNew: true,
    likes: 2345,
    shares: 112,
    comments: 67,
    createdAt: "2025-10-01T14:00:00Z",
  },
];

export const languages = [
  "all",
  "TypeScript",
  "JavaScript",
  "Python",
  "Rust",
  "Go",
  "Java",
  "C++",
];

export const techInterests = [
  "React",
  "Next.js",
  "TypeScript",
  "Python",
  "Rust",
  "Go",
  "Machine Learning",
  "DevOps",
  "Mobile",
  "Web3",
  "AI",
  "Cloud",
  "Security",
  "Database",
];
